# Generated by Django 5.2.7 on 2025-10-18 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employerfeedback',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='students.placement'),
        ),
        migrations.AddField(
            model_name='employerfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_feedbacks', to='students.student'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='students.student'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='employers.employer'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employers.jobposting'),
        ),
        migrations.AddField(
            model_name='rehirerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehirerequest',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehire_requests', to='employers.employer'),
        ),
        migrations.AddField(
            model_name='rehirerequest',
            name='previous_placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehire_requests', to='students.placement'),
        ),
        migrations.AddField(
            model_name='rehirerequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehire_requests', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_posting', 'student')},
        ),
    ]
