# Generated by Django 5.2.7 on 2025-10-18 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='certificateverification',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certifications.certificate'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='retraining_courses',
            field=models.ManyToManyField(blank=True, related_name='retraining_assessments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to='students.student'),
        ),
        migrations.AddField(
            model_name='courseaccreditation',
            name='accreditation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='certifications.accreditation'),
        ),
        migrations.AddField(
            model_name='courseaccreditation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='courseaccreditation',
            unique_together={('course', 'accreditation')},
        ),
    ]
